#!/usr/bin/env bash

git stash -q --keep-index

printf "\e[33;1m%s\e[0m\n" 'Running flutter analyze'
flutter analyze
if [ $? -ne 0 ]; then
  git stash pop -q
  printf "\e[33;1m%s\e[0m\n" 'Failed flutter analyze'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished flutter analyze'

printf "\e[33;1m%s\e[0m\n" 'Running flutter test'
flutter test
if [ $? -ne 0 ]; then
  git stash pop -q
  printf "\e[33;1m%s\e[0m\n" 'Failed flutter test'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished flutter test'

git stash pop -q
