stages:
  - test
  - build
  - deploy

.flutter:
  image: cirrusci/flutter:2.0.1
  before_script:
    - flutter config --enable-web
    - flutter packages get
    - flutter clean

test:
  stage: test
  extends: .flutter
  script:
    - flutter test

build_web:
  stage: build
  extends: .flutter
  script:
    - flutter build web
  artifacts:
    paths:
      - build/web

staging_web:
  image: node:10
  stage: deploy
  script:
    - npm i -g firebase-tools
    - firebase use --token $FIREBASE_HOSTING_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_HOSTING_KEY
  only:
    - master
