stages:
  - test
  - build
  - deploy

before_script:
  - flutter config --enable-web
  - flutter doctor
  - flutter packages get

test:
  stage: test
  script:
    - flutter test

build_web:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build web
  artifacts:
    paths:
      - build/web
  only:
    - master

staging_web:
  stage: deploy
  script:
    - npx firebase-tools
    - firebase use --token $FIREBASE_HOSTING_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_HOSTING_KEY
  tags:
    - firebase
  only:
    - master
