stages:
  - test
  - build
  - deploy

.flutter:
  image: cirrusci/flutter:3.3.9
  before_script:
    - flutter packages get
    - flutter clean

test:
  stage: test
  extends: .flutter
  script:
    - flutter test

build_web:
  stage: build
  extends: .flutter
  script:
    - flutter build web
    - echo -e "<script>(function () {document.write('<base href=\"' + document.location.pathname + '\" />');}());</script>\n$(cat build/web/index.html)" > build/web/index.html
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - main
