include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/injection.config.dart
    - lib/generated_plugin_registrant.dart
    - test/**
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
