name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.0.1
  bloc: ^7.0.0
  cloud_firestore: ^1.0.7
  dartz: ^0.10.0-nullsafety.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_staggered_grid_view: ^0.4.0
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  injectable: ^1.3.0
  intl: ^0.17.0
  meta: ^1.3.0
  url_launcher: ^6.0.3
  url_launcher_web: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^2.0.1
  bloc_test: ^8.0.0
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  injectable_generator: ^1.3.0
  lint: ^1.5.3
  mockito: ^5.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
