name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  dartz: ^0.10.0-nullsafety.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.1.3
  google_fonts: ^3.0.1
  injectable: ^2.1.0
  intl: ^0.17.0
  meta: ^1.3.0
  supabase_flutter: ^1.2.2
  url_launcher: ^6.0.3
  url_launcher_web: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  lint: ^2.0.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/licenses/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Noto Color Emoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
