name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  auto_route: ^0.6.9
  bloc: ^6.1.0
  cloud_firestore: ^0.16.0
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_staggered_grid_view: ^0.3.2
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  injectable: ^1.0.5
  intl: ^0.16.1
  meta: ^1.2.3
  url_launcher: ^5.7.10
  url_launcher_web: ">=0.1.5+1 <2.0.0"

dev_dependencies:
  auto_route_generator: ^0.6.10
  bloc_test: ^7.1.0
  # adding build_resolvers to workaround build bug
  # https://github.com/dart-lang/build/issues/2712
  # https://github.com/dart-lang/build/issues/2763
  # try removing later to see if it's fixed
  build_resolvers: ^1.3.11
  build_runner: ^1.10.4
  cloud_firestore_mocks: ^0.6.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  lint: ^1.3.0
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
