name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  auto_route: ^0.6.9
  bloc: ^7.0.0
  cloud_firestore: ^0.16.0
  dartz: ^0.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_staggered_grid_view: ^0.3.4
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  injectable: ^1.0.7
  intl: ^0.17.0
  meta: ^1.2.4
  url_launcher: ^6.0.3
  url_launcher_web: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^0.6.10
  bloc_test: ^8.0.0
  build_runner: ^1.11.1
  cloud_firestore_mocks: ^0.6.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  lint: ^1.5.1
  mockito: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
