// Mocks generated by Mockito 5.0.5 from annotations
// in portfolio/test/data/network/projects/firestore_projects_repository_test.dart.
// Do not manually edit this file.

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio/data/network/projects/firestore_project_parser.dart' as _i3;
import 'package:portfolio/domain/projects/entities/project.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeProject extends _i1.Fake implements _i2.Project {}

/// A class which mocks [FirestoreProjectParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreProjectParser extends _i1.Mock implements _i3.FirestoreProjectParser {
  MockFirestoreProjectParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Project parseProject(_i4.DocumentSnapshot? projectDoc, List<_i4.DocumentSnapshot>? tagsDoc) =>
      (super.noSuchMethod(Invocation.method(#parseProject, [projectDoc, tagsDoc]), returnValue: _FakeProject())
          as _i2.Project);
}
