name: Deploy Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.37.1

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase functions deploy experiences
      - run: supabase functions deploy projects
